# permissions for end users to view sushrutawsec2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sushrutawsec2-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatortag
    app.kubernetes.io/part-of: operatortag
    app.kubernetes.io/managed-by: kustomize
  name: sushrutawsec2-viewer-role
rules:
- apiGroups:
  - aws.sushrut.com
  resources:
  - sushrutawsec2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.sushrut.com
  resources:
  - sushrutawsec2s/status
  verbs:
  - get
