apiVersion: aws.sushrut.com/v1
kind: SushrutAWSEC2
metadata:
  labels:
    app.kubernetes.io/name: sushrutawsec2
    app.kubernetes.io/instance: sushrutawsec2-sample
    app.kubernetes.io/part-of: operatortag
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operatortag
  name: sushrutawsec2-sample
spec:
  # TODO(user): Add fields here
